export const TASK_TOGGLE = 'TASK_TOGGLE';
export const TASK_DELETE = 'TASK_DELETE';
export const TASK_ADD = 'TASK_ADD';

export const COUNT_DELETED_TASKS = 'COUNT_DELETED_TASKS';
export const COUNT_ADD_TASKS = 'COUNT_ADD_TASKS';
export const COUNT_DONE_TASKS = 'COUNT_DONE_TASKS';

export const FETCH_INITIAL_TASKS = 'FETCH_INITIAL_TASKS';
